
CREATE TABLE IF NOT EXISTS Roles (
    Id SERIAL PRIMARY KEY,
    Name VARCHAR(50) NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS Permissions (
    Id SERIAL PRIMARY KEY,
    Name VARCHAR(50) NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS RolePermissions (
    RoleId INT NOT NULL,
    PermissionId INT NOT NULL,
    PRIMARY KEY (RoleId, PermissionId),
    FOREIGN KEY (RoleId) REFERENCES Roles(Id) ON DELETE CASCADE,
    FOREIGN KEY (PermissionId) REFERENCES Permissions(Id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS Users (
    Id SERIAL PRIMARY KEY,
    Name VARCHAR(100) NOT NULL,
    Email VARCHAR(150) NOT NULL UNIQUE,
    Username VARCHAR(50) NOT NULL UNIQUE,
    PasswordHash VARCHAR(255) NOT NULL,
    RoleId INT NOT NULL,
    IsActive BOOLEAN DEFAULT TRUE,
    CreatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (RoleId) REFERENCES Roles(Id)
);

CREATE TABLE IF NOT EXISTS RefreshTokens (
    Id SERIAL PRIMARY KEY,
    Token VARCHAR(255) NOT NULL UNIQUE,
    UserId INT NOT NULL,
    ExpiryDate TIMESTAMP NOT NULL,
    IsRevoked BOOLEAN DEFAULT FALSE,
    FOREIGN KEY (UserId) REFERENCES Users(Id) ON DELETE CASCADE
);

INSERT INTO Roles (Name) VALUES ('Admin'), ('User') ON CONFLICT DO NOTHING;
INSERT INTO Permissions (Name) VALUES ('Read'), ('Write'), ('Delete') ON CONFLICT DO NOTHING;

-- Assign all to Admin (Id 1)
INSERT INTO RolePermissions (RoleId, PermissionId) VALUES (1, 1), (1, 2), (1, 3) ON CONFLICT DO NOTHING;
-- Assign Read to User (Id 2)
INSERT INTO RolePermissions (RoleId, PermissionId) VALUES (2, 1) ON CONFLICT DO NOTHING;
